# Generated by Django 2.2 on 2020-02-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200212_1607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
